# Generated by Django 3.2.7 on 2021-10-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0024_individual_car_details_showimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isDealer',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='AddharNumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
